### PR TITLE
fix macos build and enable arm optimization

### PR DESCRIPTION
**Pull request by yuygfgg**

### CODE REVIEW

**Comment by WolframRhodium** [comment]
Why use `-fopenmp`?

**Comment by yuygfgg** [comment]
> Why use `-fopenmp`?

Sorry it's a mistake.

**Comment by WolframRhodium** [comment]
The pr prevents compilation on Windows using the existing ci:
```
Run meson setup builddir/ -Db_vscrt=mt -Dpkg_config_path=D:\a\fft3d\fft3d/vcpkg/installed/x64-windows-static/lib/pkgconfig
  
The Meson build system
Version: 1.5.1
Source dir: D:\a\fft3d\fft3d
Build dir: D:\a\fft3d\fft3d\builddir
Build type: native build
Project name: FFT3DFilter
Project version: 2
C++ compiler for the host machine: clang-cl (clang-cl 18.1.8)
C++ linker for the host machine: lld-link lld-link 18.1.8
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (C:\ProgramData\Chocolatey\bin\pkg-config.EXE) 0.28
Run-time dependency fftwf found: YES 3.3.7
Library fftw3f_threads found: NO
meson.build:53:2: ERROR: Problem encountered: fftw3f_threads library not found.
A full log can be found at D:\a\fft3d\fft3d\builddir\meson-logs\meson-log.txt
Error: Process completed with exit code 1.
```

Please don't change
```
if not cc.links(code, dependencies : fftw3f_dep)
  deps += cc.find_library('fftw3f_threads')
```
on non-macos platforms.

**Comment by WolframRhodium** [comment]
Please fix the indentation. An `endif` command is also missing after line 56.

**Comment by WolframRhodium** [comment]
```
Run meson setup builddir/ -Db_vscrt=mt -Dpkg_config_path=D:\a\fft3d\fft3d/vcpkg/installed/x64-windows-static/lib/pkgconfig
  
The Meson build system
Version: 1.5.1
Source dir: D:\a\fft3d\fft3d
Build dir: D:\a\fft3d\fft3d\builddir
Build type: native build
Project name: FFT3DFilter
Project version: 2
C++ compiler for the host machine: clang-cl (clang-cl 18.1.8)
C++ linker for the host machine: lld-link lld-link 18.1.8
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (C:\ProgramData\Chocolatey\bin\pkg-config.EXE) 0.28
Run-time dependency fftwf found: YES 3.3.7
meson.build:48:28: ERROR: Unknown variable "fftw3f_threads_dep".
A full log can be found at D:\a\fft3d\fft3d\builddir\meson-logs\meson-log.txt
Error: Process completed with exit code 1.
```

**Comment by yuygfgg** [comment]
> ```
> Run meson setup builddir/ -Db_vscrt=mt -Dpkg_config_path=D:\a\fft3d\fft3d/vcpkg/installed/x64-windows-static/lib/pkgconfig
>   
> The Meson build system
> Version: 1.5.1
> Source dir: D:\a\fft3d\fft3d
> Build dir: D:\a\fft3d\fft3d\builddir
> Build type: native build
> Project name: FFT3DFilter
> Project version: 2
> C++ compiler for the host machine: clang-cl (clang-cl 18.1.8)
> C++ linker for the host machine: lld-link lld-link 18.1.8
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> Found pkg-config: YES (C:\ProgramData\Chocolatey\bin\pkg-config.EXE) 0.28
> Run-time dependency fftwf found: YES 3.3.7
> meson.build:48:28: ERROR: Unknown variable "fftw3f_threads_dep".
> A full log can be found at D:\a\fft3d\fft3d\builddir\meson-logs\meson-log.txt
> Error: Process completed with exit code 1.
> ```

Please wait a moment. I will comment here after tested with github CL and fixed.

**Comment by WolframRhodium** [comment]
Thanks for your contribution!

**Comment by yuygfgg** [comment]
Maybe we can close #2 now.

**Pull request merged**
